version: '3'
services:
  frontend-dev:
    build:
      context: ./virtual-store-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend-dev:
    build:
      context: ./virtual-store-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"